### ISSUE TITLE
Private content does not work

### ISSUE THREAD

**Issue by johniez** [alexanderjulo/wiki#61]
For current version: https://github.com/alexanderjulo/wiki/tree/v2.0.1
When content/config.py has `PRIVATE=True` settings:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/home/johniez/sources/alex-wiki/wiki/web/user.py", line 146, in wrapper
    return loginmanager.unauthorized()
NameError: global name 'loginmanager' is not defined
```

**Comment by johniez** [comment]
Versions of flask:
```
Flask==0.10.1
Flask-Login==0.2.6
Flask-Script==0.6.7
Flask-WTF==0.12
```

**Comment by hugohonorem** [comment]
`PRIVATE=True` throws the following error: 

```
Traceback (most recent call last):
  File "/wiki/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/wiki/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/wiki/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/wiki/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/wiki/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/wiki/venv/lib/python2.7/site-packages/wiki/web/user.py", line 145, in wrapper
    if current_app.config.get('PRIVATE') and not current_user.is_authenticated():
TypeError: 'bool' object is not callable

```

**Comment by johniez** [comment]
If I remember it correctly, `current_user.is_authenticated()` depends on flask_login version (some have property, some function)...
