### ISSUE TITLE
Template File cannot be found

### ISSUE THREAD

**Issue by PurgingPanda** [alexanderjulo/wiki#68]
```$ sudo wiki web
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2017-01-21 23:01:25,688] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/wiki/web/user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/wiki/web/routes.py", line 35, in home
    return render_template('home.html')
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [21/Jan/2017 23:01:25] "GET / HTTP/1.1" 500 -
[2017-01-21 23:01:26,060] ERROR in app: Exception on /favicon.ico/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/wiki/web/user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/wiki/web/routes.py", line 48, in display
    page = current_wiki.get_or_404(url)
  File "/usr/local/lib/python3.5/dist-packages/wiki/core.py", line 205, in get_or_404
    abort(404)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/exceptions.py", line 646, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/usr/local/lib/python3.5/dist-packages/wiki/web/routes.py", line 182, in page_not_found
    return render_template('404.html'), 404
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
127.0.0.1 - - [21/Jan/2017 23:01:26] "GET /favicon.ico/ HTTP/1.1" 500 -
```

**Comment by alexanderjulo** [comment]
@PurgingPanda thanks for reporting this and sorry for me slow response! Would you mind quickly adding some information on how you installed wiki, how you run it, eventual configuration and some info on your OS? It looks like a Mac, but I want to make sure. 🙂

**Comment by jjgalvez** [comment]
getting the same issue. running on ubuntu 16.04, python 3.5 in a vertualenv, installed with pip wiki2 created the config.py file and ran wiki web.

`Traceback (most recent call last):
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/wiki/web/user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/wiki/web/routes.py", line 35, in home
    return render_template('home.html')
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/jc/dev/wiki/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html`

**Comment by tkerwin** [comment]
I see the same error with python 3.6, running on Windows 10.

**Comment by alexanderjulo** [comment]
Hey guys, can you update to v2.0.3 and check again? Theoretically this should be fixed now. 🙂 Sorry for the delay!
