### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by bmcculley** [alexanderjulo/wiki#75]
I was messing around with the tests some, it seems to be an upstream issue with pytest_runner that causes tests on python 3.3 to fail. The error:

```
travis@93b9068ce8dd:~/wiki-master$ python setup.py test
['tests', 'wiki', 'wiki.web']
running pytest
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    'wiki=wiki.cli:main'
  File "/home/travis/opt/python/3.3.6/lib/python3.3/distutils/core.py", line 147, in setup
    dist.run_commands()
  File "/home/travis/opt/python/3.3.6/lib/python3.3/distutils/dist.py", line 930, in run_commands
    self.run_command(cmd)
  File "/home/travis/opt/python/3.3.6/lib/python3.3/distutils/dist.py", line 949, in run_command
    cmd_obj.run()
  File "/home/travis/wiki-master/.eggs/pytest_runner-4.0-py3.3.egg/ptr.py", line 157, in run
  File "/home/travis/wiki-master/.eggs/pytest_runner-4.0-py3.3.egg/ptr.py", line 118, in install_dists
AttributeError: type object 'test' has no attribute 'install_dists'
```
I created a new branch which removed 3.3 testing, is there any reason we should keep testing 3.3? If so maybe an upstream ticket should be opened to resolve this? Interestingly python 3.3 testing behaves differently if ran directly or using a virtualenv (all tests pass using a virtualenv) I'll clean up the dockerfile I was using for testing, create a gist and post the link here so others can easily have a look.

Second issue is that tests are still failing on python 3.4 on windows. I haven't had time to dig into that as much as I don't have windows test machines setup, maybe I'll setup some virtual machines later. But in the appveyor logs it looks like there's a problem with jinja2 and then it also seems to fail with 

```
File "c:\projects\wiki\.eggs\pytest_runner-4.0-py3.4.egg\ptr.py", line 157, in run
  File "c:\projects\wiki\.eggs\pytest_runner-4.0-py3.4.egg\ptr.py", line 118, in install_dists
AttributeError: type object 'test' has no attribute 'install_dists'
```
which is the same error python 3.3 was throwing on linux.

**Comment by bmcculley** [comment]
Opened pull request #77 to fix this, turns out that it was setuptools causing these issues. Just need to update it before running the tests.

**Comment by bmcculley** [comment]
I think this can be closed now, the tests seem to be working again.
