### ISSUE TITLE
500 error  when  save the first post,please help

### ISSUE THREAD

**Issue by listenfree** [alexanderjulo/wiki#80]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wiki/web/user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wiki/web/routes.py", line 71, in edit
    page.save()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wiki/core.py", line 199, in save
    self.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wiki/core.py", line 184, in render
    processor = Processor(self.content)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wiki/core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes 1 positional argument but 2 were given
127.0.0.1 - - [11/Jan/2019 17:59:09] "POST /edit/dd/ HTTP/1.1" 500 -
```

`config.py`:
```
# encoding: utf-8
SECRET_KEY='a unique and long key'
TITLE='Wiki' # Title Optional
```

**Comment by tobyqin** [comment]
The dependencies are outdated, you can clone my fork and run locally.

- https://github.com/tobyqin/pywiki

**Comment by alexanderjulo** [comment]
This should be resolved now. Please re-open if that's not the case.
