### ISSUE TITLE
Can't add page:

### ISSUE THREAD

**Issue by arduino5144** [alexanderjulo/wiki#90]
Adds a md file, but I can't access it via the page.

```
PS D:\Leonard\OneDrive\Dokument\random flask wiki thing\content> wiki web
Traceback (most recent call last):
  File "C:\Python27\Scripts\wiki-script.py", line 11, in <module>
    load_entry_point('wiki2==2.0.3', 'console_scripts', 'wiki')()
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\cli.py", line 38, in web
    app = create_app(ctx.meta['directory'])
  File "c:\python27\lib\site-packages\wiki\web\__init__.py", line 38, in create_app
    os.path.join(app.config.get('CONTENT_DIR'), 'config.py')
  File "c:\python27\lib\site-packages\flask\config.py", line 132, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "D:\Leonard\OneDrive\Dokument\random flask wiki thing\content\config.py", line 2, in <module>
    SECRET_KEY=JvoGTgriz6yn8WsJhOdf9gHv4A5f8braI2jA9IPNSE2ZT8MMqgVpSqFxf6lzR4hicD0rlxMAGHI61PAyrs5gr0h0sYFqqlum8EAP
NameError: name 'JvoGTgriz6yn8WsJhOdf9gHv4A5f8braI2jA9IPNSE2ZT8MMqgVpSqFxf6lzR4hicD0rlxMAGHI61PAyrs5gr0h0sYFqqlum8EAP' is not defined
PS D:\Leonard\OneDrive\Dokument\random flask wiki thing\content> wiki web
 * Serving Flask app "wiki.web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Nov/2020 13:14:16] "←[37mGET / HTTP/1.1←[0m" 200 -
127.0.0.1 - - [30/Nov/2020 13:14:18] "←[37mGET /static/pygments.css HTTP/1.1←[0m" 200 -
127.0.0.1 - - [30/Nov/2020 13:14:18] "←[37mGET /static/responsive.css HTTP/1.1←[0m" 200 -
127.0.0.1 - - [30/Nov/2020 13:14:18] "←[37mGET /static/bootstrap.css HTTP/1.1←[0m" 200 -
127.0.0.1 - - [30/Nov/2020 13:14:18] "←[37mGET /static/bootstrap.min.js HTTP/1.1←[0m" 200 -
127.0.0.1 - - [30/Nov/2020 13:14:19] "←[32mGET /favicon.ico HTTP/1.1←[0m" 308 -
127.0.0.1 - - [30/Nov/2020 13:14:19] "←[33mGET /favicon.ico/ HTTP/1.1←[0m" 404 -
c:\python27\lib\site-packages\wiki\web\routes.py:66: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = EditorForm(obj=page)
127.0.0.1 - - [30/Nov/2020 13:14:25] "←[37mGET /edit/home/ HTTP/1.1←[0m" 200 -
c:\python27\lib\site-packages\wiki\web\routes.py:66: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = EditorForm(obj=page)
[2020-11-30 13:14:54,778] ERROR in app: Exception on /edit/home/ [POST]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 71, in edit
    page.save()
  File "c:\python27\lib\site-packages\wiki\core.py", line 199, in save
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:14:54] "←[35m←[1mPOST /edit/home/ HTTP/1.1←[0m" 500 -
[2020-11-30 13:15:23,920] ERROR in app: Exception on /edit/home/ [POST]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 65, in edit
    page = current_wiki.get(url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 255, in get
    return Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:15:23] "←[35m←[1mPOST /edit/home/ HTTP/1.1←[0m" 500 -
[2020-11-30 13:15:27,490] ERROR in app: Exception on /edit/home/ [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 65, in edit
    page = current_wiki.get(url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 255, in get
    return Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:15:27] "←[35m←[1mGET /edit/home/ HTTP/1.1←[0m" 500 -
c:\python27\lib\site-packages\wiki\web\routes.py:134: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = LoginForm()
127.0.0.1 - - [30/Nov/2020 13:15:33] "←[37mGET /user/login/ HTTP/1.1←[0m" 200 -
c:\python27\lib\site-packages\wiki\web\routes.py:55: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = URLForm()
127.0.0.1 - - [30/Nov/2020 13:15:35] "←[37mGET /create/ HTTP/1.1←[0m" 200 -
c:\python27\lib\site-packages\wiki\web\routes.py:55: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = URLForm()
127.0.0.1 - - [30/Nov/2020 13:15:41] "←[32mPOST /create/ HTTP/1.1←[0m" 302 -
c:\python27\lib\site-packages\wiki\web\routes.py:66: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = EditorForm(obj=page)
127.0.0.1 - - [30/Nov/2020 13:15:41] "←[37mGET /edit/e/ HTTP/1.1←[0m" 200 -
c:\python27\lib\site-packages\wiki\web\routes.py:66: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = EditorForm(obj=page)
[2020-11-30 13:15:44,602] ERROR in app: Exception on /edit/e/ [POST]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 71, in edit
    page.save()
  File "c:\python27\lib\site-packages\wiki\core.py", line 199, in save
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:15:44] "←[35m←[1mPOST /edit/e/ HTTP/1.1←[0m" 500 -
PS D:\Leonard\OneDrive\Dokument\random flask wiki thing\content> wiki web
 * Serving Flask app "wiki.web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-11-30 13:16:47,305] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 32, in home
    page = current_wiki.get('home')
  File "c:\python27\lib\site-packages\wiki\core.py", line 255, in get
    return Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:16:47] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
[2020-11-30 13:16:58,552] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 32, in home
    page = current_wiki.get('home')
  File "c:\python27\lib\site-packages\wiki\core.py", line 255, in get
    return Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:16:58] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
[2020-11-30 13:17:20,540] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 32, in home
    page = current_wiki.get('home')
  File "c:\python27\lib\site-packages\wiki\core.py", line 255, in get
    return Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:17:20] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
127.0.0.1 - - [30/Nov/2020 13:17:31] "←[32mGET /wiki HTTP/1.1←[0m" 308 -
127.0.0.1 - - [30/Nov/2020 13:17:32] "←[33mGET /wiki/ HTTP/1.1←[0m" 404 -
[2020-11-30 13:17:36,720] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 32, in home
    page = current_wiki.get('home')
  File "c:\python27\lib\site-packages\wiki\core.py", line 255, in get
    return Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:17:36] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
127.0.0.1 - - [30/Nov/2020 13:17:38] "←[33mGET /wiki/ HTTP/1.1←[0m" 404 -
[2020-11-30 13:17:40,086] ERROR in app: Exception on /index/ [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 41, in index
    pages = current_wiki.index()
  File "c:\python27\lib\site-packages\wiki\core.py", line 316, in index
    page = Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:17:40] "←[35m←[1mGET /index/ HTTP/1.1←[0m" 500 -
127.0.0.1 - - [30/Nov/2020 13:17:41] "←[33mGET /wiki/ HTTP/1.1←[0m" 404 -
127.0.0.1 - - [30/Nov/2020 13:17:44] "←[32mGET /wiki/e HTTP/1.1←[0m" 308 -
127.0.0.1 - - [30/Nov/2020 13:17:44] "←[33mGET /wiki/e/ HTTP/1.1←[0m" 404 -
[2020-11-30 13:17:54,742] ERROR in app: Exception on /e/ [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\wiki\web\user.py", line 147, in wrapper
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\wiki\web\routes.py", line 48, in display
    page = current_wiki.get_or_404(url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 259, in get_or_404
    page = self.get(url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 255, in get
    return Page(path, url)
  File "c:\python27\lib\site-packages\wiki\core.py", line 174, in __init__
    self.render()
  File "c:\python27\lib\site-packages\wiki\core.py", line 184, in render
    processor = Processor(self.content)
  File "c:\python27\lib\site-packages\wiki\core.py", line 92, in __init__
    'tables'
TypeError: __init__() takes exactly 1 argument (2 given)
127.0.0.1 - - [30/Nov/2020 13:17:54] "←[35m←[1mGET /e/ HTTP/1.1←[0m" 500 -
127.0.0.1 - - [30/Nov/2020 13:17:56] "←[33mGET /wiki/e/ HTTP/1.1←[0m" 404 -
```

**Comment by alexanderjulo** [comment]
Hey @arduino5144. 🙂 

the configuration file is a python file, so you need to quote strings in it like such:

```python
SECRET_KEY="JvoGTgriz6yn8WsJhOdf9gHv4A5f8braI2jA9IPNSE2ZT8MMqgVpSqFxf6lzR4hicD0rlxMAGHI61PAyrs5gr0h0sYFqqlum8EAP"
```

However it looks like there is another bug there as well. Can you tell me how you installed wiki? Via `pip` or by pulling the git repo?

**Comment by arduino5144** [comment]
Pip

**Comment by alexanderjulo** [comment]
@arduino5144 this issue should already have been resolved in the master branch, so if you install it from the github repo, it should not appear. I will make sure to release an update some time soon to address this also on pip
